[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

[dev]
  command = "yarn develop" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  targetPort = 3000 # Port of target app server
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
  jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
